const VARS={ph:{label:'pH',unit:'pH',color:'#006d77'},conductividad_us_cm:{label:'Conductividad eléctrica',unit:'µS/cm',color:'#178da0'},temperatura_agua_c:{label:'Temperatura del agua',unit:'°C',color:'#e58b35'},oxigeno_disuelto_mg_l:{label:'Oxígeno disuelto',unit:'mg/L',color:'#3f72af'},distancia_agua_m:{label:'Distancia al agua',unit:'m',color:'#176e9a'},profundidad_m:{label:'Profundidad',unit:'m',color:'#006d77'},temperatura_aire_c:{label:'Temperatura del aire',unit:'°C',color:'#e58b35'},humedad_aire_pct:{label:'Humedad del aire',unit:'%',color:'#748fb4'},temperatura_sistema_c:{label:'Temperatura del sistema',unit:'°C',color:'#875d9d'},voltaje_v:{label:'Voltaje',unit:'V',color:'#b88916'},senal_csq:{label:'Señal celular',unit:'CSQ',color:'#59727d'}};
const API='https://api-sensores.cmasccp.cl/listarDatosEstructuradosV2';
const LIVE_FIELDS={
 'AGUA':{ph:'ENV-20-pH [pH ambiental (pH)]',conductividad_us_cm:'ENV-20-EC-K1.0 [Electroconductividad (uS/cm)]',temperatura_agua_c:'DS18B20 [Grados celcius (°C)]',oxigeno_disuelto_mg_l:'ENV-40-DOX [Oxígeno Disuelto (mg/L)]',temperatura_sistema_c:'DS3231 [Grados celcius (°C)]',voltaje_v:'Divisor de Voltaje [Voltaje (V)]',senal_csq:'SIM7600G [Intensidad señal telefónica (Adimensional)]'},
 'URA':{ph:'CWT-BL-PH(T)-S [pH ambiental (pH)]',conductividad_us_cm:'CWT-BL-EC-15K-S [Electroconductividad (uS/cm)]',temperatura_agua_c:'CWT-BL-PH(T)-S [Grados celcius (°C)]',temperatura_sistema_c:'DS3231 [Grados celcius (°C)]',voltaje_v:'Divisor de Voltaje [Voltaje (V)]',senal_csq:'SIM7600G [Intensidad señal telefónica (Adimensional)]'},
 'LVAG':{distancia_agua_m:'A01NYUB [Distancia (m)]',profundidad_m:'LIQ-136 [Profundidad (m)]',temperatura_aire_c:'SHT40 [Grados celcius (°C)]',humedad_aire_pct:'SHT40 [Humedad (%)]',temperatura_sistema_c:'DS3231 [Grados celcius (°C)]',voltaje_v:'Divisor de Voltaje [Voltaje (V)]',senal_csq:'SIM7600G [Intensidad señal telefónica (Adimensional)]'}};
let manifest,stations=[],selected=0,chart,map,markers=[],markerBySite={},cache={},latest={},renderVersion=0;
const $=id=>document.getElementById(id), num=v=>{let n=parseFloat(v);return Number.isFinite(n)?n:null};
function csv(text){let lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];let h=lines.shift().split(',');return lines.map(line=>{let c=line.split(','),o={};h.forEach((k,i)=>o[k]=c[i]||'');return o})}
function markerIcon(active){return L.divIcon({className:'',html:`<div style="width:18px;height:18px;border:3px solid white;border-radius:50%;background:${active?'#38b7b0':'#006d77'};box-shadow:0 2px 8px #1238"></div>`,iconSize:[18,18]})}
function setupMap(){map=L.map('map').setView([-33.25,-71.05],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);let sites={};stations.forEach((s,i)=>(sites[s.site]??=[]).push(i));Object.entries(sites).forEach(([site,indexes])=>{let s=stations[indexes[0]],m=L.marker([s.lat,s.lng],{icon:markerIcon(false)}).addTo(map);let popup=document.createElement('div');popup.className='map-stations';let heading=document.createElement('strong');heading.textContent=s.context.replace('Línea Base Pública – ','');popup.append(heading);indexes.forEach(i=>{let button=document.createElement('button');button.type='button';button.textContent=`${stations[i].name} · ${stations[i].code}`;button.onclick=()=>choose(i);popup.append(button)});m.bindPopup(popup);markerBySite[site]=m;markers.push(m)});let group=L.featureGroup(markers);map.fitBounds(group.getBounds().pad(.2))}
function choose(i){selected=i;$('station-select').value=i;Object.entries(markerBySite).forEach(([site,m])=>m.setIcon(markerIcon(site===stations[i].site)));document.querySelectorAll('.station-item').forEach((el,j)=>{el.classList.toggle('active',j===i);el.setAttribute('aria-current',j===i?'true':'false')});markerBySite[stations[i].site].openPopup();renderStation()}
function pathsFor(s,period){let all=Object.entries(s.months||{}).sort();if(period==='all')return all.flatMap(x=>x[1]);let days=period==='24h'?1:period==='7d'?7:30,base=new Date(manifest.updated_at.replace(' ','T')).getTime(),cut=base-days*864e5;return all.filter(([m])=>{let [y,mo]=m.split('-').map(Number);return new Date(y,mo,1).getTime()>cut}).flatMap(x=>x[1])}
async function rowsFor(s,period){let key=s.code+'|'+period;if(cache[key])return cache[key];let groups=await Promise.all(pathsFor(s,period).map(p=>fetch(p+'?v='+encodeURIComponent(manifest.updated_at)).then(r=>{if(!r.ok)throw Error(r.status);return r.text()}).then(csv)));let rows=groups.flat().sort((a,b)=>new Date(a.fecha)-new Date(b.fecha));if(period!=='all'){let days=period==='24h'?1:period==='7d'?7:30,base=new Date(manifest.updated_at.replace(' ','T')).getTime(),cut=base-days*864e5;rows=rows.filter(r=>new Date(r.fecha)>=cut)}cache[key]=rows;return rows}
function fillVariables(s){let sel=$('variable-select'),current=sel.value;sel.innerHTML='';s.variables.forEach(k=>{if(VARS[k])sel.add(new Option(VARS[k].label,k))});if(s.variables.includes(current))sel.value=current;else if(s.code.startsWith('LVAG'))sel.value='profundidad_m'}
function chartData(points,period,color,label){if(period==='24h'||period==='7d')return{labels:points.map(p=>p.x),datasets:[{label:'Mediciones',data:points.map(p=>p.y),borderColor:color,backgroundColor:color+'18',fill:true,pointRadius:points.length>180?0:2,tension:.18}],daily:false};let groups={};points.forEach(p=>{let day=p.x.slice(0,10);(groups[day]??=[]).push(p.y)});let days=Object.keys(groups).sort(),avg=days.map(day=>groups[day].reduce((a,b)=>a+b,0)/groups[day].length),mins=days.map(day=>Math.min(...groups[day])),maxs=days.map(day=>Math.max(...groups[day]));return{labels:days,daily:true,datasets:[{label:'Mínimo diario',data:mins,borderColor:'transparent',pointRadius:0,fill:false},{label:'Rango diario',data:maxs,borderColor:'transparent',backgroundColor:color+'2b',pointRadius:0,fill:'-1'},{label:'Promedio diario',data:avg,borderColor:color,backgroundColor:'transparent',pointRadius:avg.length>100?0:2,tension:.18,borderWidth:2}]}}
async function renderStation(){let version=++renderVersion,s=stations[selected];$('station-title').textContent=s.name;$('station-context').textContent=s.context+' · '+s.project;fillVariables(s);let key=$('variable-select').value,period=$('period-select').value,v=VARS[key];if(!v){$('chart-empty').hidden=false;$('chart-empty').textContent='Aún no hay variables disponibles para esta estación.';return}try{let rows=await rowsFor(s,period);if(version!==renderVersion)return;let points=rows.map(r=>({x:r.fecha,y:num(r[key])})).filter(p=>p.y!==null),live=latest[s.code]?.[key],days=period==='24h'?1:period==='7d'?7:period==='30d'?30:null,cut=days?new Date(manifest.updated_at.replace(' ','T')).getTime()-days*864e5:null;if(live&&(cut===null||new Date(live.fecha).getTime()>=cut)&&!points.some(p=>p.x===live.fecha))points.push({x:live.fecha,y:live.valor});points.sort((a,b)=>new Date(a.x)-new Date(b.x));let last=points.at(-1),display=chartData(points,period,v.color,v.label);$('last-value').textContent=last?`${last.y.toLocaleString('es-CL',{maximumFractionDigits:2})} ${v.unit}`:'—';$('last-time').textContent=last?new Date(last.x).toLocaleString('es-CL'):'Sin medición válida';$('availability').textContent=points.length?'Con datos':'Sin datos';$('record-count').textContent=`${points.length.toLocaleString('es-CL')} observaciones válidas`;$('chart-empty').hidden=!!points.length;if(chart)chart.destroy();chart=new Chart($('chart'),{type:'line',data:{labels:display.labels,datasets:display.datasets},options:{responsive:true,maintainAspectRatio:false,scales:{x:{type:'category',ticks:{maxTicksLimit:8,callback(i){let raw=display.labels[i];return raw?new Date(raw+(raw.length===10?'T00:00:00':'')).toLocaleDateString('es-CL'):''}},grid:{display:false}},y:{title:{display:true,text:v.unit}}},plugins:{legend:{display:display.daily,labels:{filter:item=>item.text!=='Mínimo diario'}},title:{display:true,text:display.daily?'Promedio diario y rango mínimo–máximo':'Mediciones individuales'},tooltip:{callbacks:{title(items){let raw=items[0].label;return new Date(raw+(raw.length===10?'T00:00:00':'')).toLocaleString('es-CL')}}}}}})}catch(e){console.error(e);$('chart-empty').hidden=false;$('chart-empty').textContent='No fue posible cargar los datos.'}}
function cleanLive(key,value,type){value=num(value);if(value===null)return null;if(key==='ph'&&(value<=0||value>=14))return null;if(key==='conductividad_us_cm'&&value<=0)return null;if(key==='temperatura_agua_c'&&type==='AGUA'&&(value<=0||value>60))return null;if(key==='temperatura_sistema_c'&&(value<=-30||value>85))return null;if(key==='temperatura_aire_c'&&(value<=-30||value>60))return null;if(key==='humedad_aire_pct'&&(value<0||value>100))return null;if((key==='distancia_agua_m'||key==='profundidad_m')&&(value<0||value>100))return null;return value}
async function liveStation(s){let type=s.code.startsWith('LVAG')?'LVAG':s.code.startsWith('URA')?'URA':'AGUA',url=`${API}?tabla=datos&disp.id_proyecto=${s.project_id}&disp.codigo_interno=${encodeURIComponent(s.code)}&order_by=fecha_insercion&limite=1`;let j=await fetch(url,{cache:'no-store'}).then(r=>r.json()),row=j?.data?.tableData?.[0];if(!row)return;latest[s.code]??={};Object.entries(LIVE_FIELDS[type]).forEach(([k,f])=>{let val=cleanLive(k,row[f],type);if(val!==null)latest[s.code][k]={fecha:row.fecha,valor:val}});return row.fecha}
async function refreshLive(){let results=await Promise.allSettled(stations.map(liveStation)),times=results.filter(r=>r.status==='fulfilled'&&r.value).map(r=>r.value);results.forEach((r,i)=>{if(r.status==='rejected')console.warn('En vivo',stations[i].code,r.reason)});if(times.length){$('live-dot').style.background='#37c694';$('live-label').textContent='Datos en vivo';$('updated').textContent=new Date(times.sort().at(-1)).toLocaleString('es-CL');renderStation()}else{$('live-label').textContent='Histórico horario'}}
function csvText(rows){let keys=Object.keys(rows[0]||{});return keys.join(',')+'\n'+rows.map(r=>keys.map(k=>r[k]??'').join(',')).join('\n')}
function saveBlob(name,blob){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function download(name,rows){saveBlob(name,new Blob(['\ufeff'+csvText(rows)],{type:'text/csv'}))}
async function downloadSelection(){if(!confirm('Datos preliminares con incertidumbre y posibles correcciones. El licenciamiento abierto propuesto continúa en revisión. ¿Deseas descargar?'))return;let s=stations[selected],rows=(await rowsFor(s,$('period-select').value)).map(r=>({estacion:s.code,...r}));if(rows.length)download(`${s.code}_${$('period-select').value}.csv`,rows)}
async function downloadAll(){if(!confirm('Descargarás un ZIP con un CSV independiente por estación. Los datos son preliminares y el licenciamiento propuesto continúa en revisión. ¿Deseas continuar?'))return;let button=$('download-all');button.disabled=true;button.textContent='Preparando ZIP…';try{let zip=new JSZip();for(let s of stations){let rows=(await rowsFor(s,'all')).map(r=>({estacion:s.code,...r}));if(rows.length)zip.file(`${s.code}.csv`,'\ufeff'+csvText(rows))}let blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});saveBlob('calidad_agua_por_estacion.zip',blob)}finally{button.disabled=false;button.textContent='Descargar todos por estación (.zip)'}}
async function init(){let [m,l]=await Promise.all([fetch('data/manifest.json?v='+Date.now()).then(r=>r.json()),fetch('data/latest.csv?v='+Date.now()).then(r=>r.text())]);manifest=m;stations=m.stations;csv(l).forEach(r=>{latest[r.codigo]??={};latest[r.codigo][r.variable]={fecha:r.fecha,valor:num(r.valor)}});$('updated').textContent=m.updated_at?new Date(m.updated_at).toLocaleString('es-CL'):'—';stations.forEach((s,i)=>{$('station-select').add(new Option(`${s.name} · ${s.code}`,i));let button=document.createElement('button');button.type='button';button.className='station-item';button.innerHTML=`<span><b></b><br><small></small></span><span class="station-code"></span>`;button.querySelector('b').textContent=s.name;button.querySelector('small').textContent=s.context;button.querySelector('.station-code').textContent=s.code;button.onclick=()=>choose(i);$('station-list').append(button)});setupMap();choose(0);refreshLive();setInterval(refreshLive,600000)}
$('station-select').onchange=e=>choose(+e.target.value);$('variable-select').onchange=renderStation;$('period-select').onchange=renderStation;$('download-selection').onclick=downloadSelection;$('download-all').onclick=downloadAll;init().catch(e=>{$('live-label').textContent='Datos no disponibles';console.error(e)});
$('photos-prev').onclick=()=>scrollPhotos(-1);$('photos-next').onclick=()=>scrollPhotos(1);
function scrollPhotos(direction){let track=$('site-carousel'),card=track.querySelector('figure');track.scrollBy({left:direction*(card.getBoundingClientRect().width+16),behavior:'smooth'})}
