const VARS={ph:{label:'pH',unit:'pH',color:'#006d77'},conductividad_us_cm:{label:'Conductividad eléctrica',unit:'µS/cm',color:'#178da0'},temperatura_agua_c:{label:'Temperatura del agua',unit:'°C',color:'#e58b35'},oxigeno_disuelto_mg_l:{label:'Oxígeno disuelto',unit:'mg/L',color:'#3f72af'},temperatura_sistema_c:{label:'Temperatura del sistema',unit:'°C',color:'#875d9d'},voltaje_v:{label:'Voltaje',unit:'V',color:'#b88916'},senal_csq:{label:'Señal celular',unit:'CSQ',color:'#59727d'}};
const API='https://api-sensores.cmasccp.cl/listarDatosEstructuradosV2';
const LIVE_FIELDS={
 'AGUA':{ph:'ENV-20-pH [pH ambiental (pH)]',conductividad_us_cm:'ENV-20-EC-K1.0 [Electroconductividad (uS/cm)]',temperatura_agua_c:'DS18B20 [Grados celcius (°C)]',oxigeno_disuelto_mg_l:'ENV-40-DOX [Oxígeno Disuelto (mg/L)]',temperatura_sistema_c:'DS3231 [Grados celcius (°C)]',voltaje_v:'Divisor de Voltaje [Voltaje (V)]',senal_csq:'SIM7600G [Intensidad señal telefónica (Adimensional)]'},
 'URA':{ph:'CWT-BL-PH(T)-S [pH ambiental (pH)]',conductividad_us_cm:'CWT-BL-EC-15K-S [Electroconductividad (uS/cm)]',temperatura_agua_c:'CWT-BL-PH(T)-S [Grados celcius (°C)]',temperatura_sistema_c:'DS3231 [Grados celcius (°C)]',voltaje_v:'Divisor de Voltaje [Voltaje (V)]',senal_csq:'SIM7600G [Intensidad señal telefónica (Adimensional)]'}};
let manifest,stations=[],selected=0,chart,map,markers=[],cache={},latest={};
const $=id=>document.getElementById(id), num=v=>{let n=parseFloat(v);return Number.isFinite(n)?n:null};
function csv(text){let lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];let h=lines.shift().split(',');return lines.map(line=>{let c=line.split(','),o={};h.forEach((k,i)=>o[k]=c[i]||'');return o})}
function norm(key,v){if(v===null)return['Sin dato','No hay una medición válida',''];if(key==='ph')return v>=5.5&&v<=9?['Dentro del rango','NCh 1333 · referencia para riego (5,5–9,0)','good']:['Fuera del rango','NCh 1333 · referencia para riego (5,5–9,0)','bad'];if(key==='conductividad_us_cm'){if(v<=750)return['Favorable','NCh 1333 · referencia para riego','good'];if(v<=1500)return['Precaución','Posibles efectos en cultivos sensibles','warn'];if(v<=3000)return['Restricción alta','Efectos adversos en numerosos cultivos','bad'];return['Restricción severa','Sobre 3.000 µS/cm · referencia para riego','bad']}return['Sin clasificación','No existe una referencia general aplicable','']}
function markerIcon(active){return L.divIcon({className:'',html:`<div style="width:18px;height:18px;border:3px solid white;border-radius:50%;background:${active?'#38b7b0':'#006d77'};box-shadow:0 2px 8px #1238"></div>`,iconSize:[18,18]})}
function setupMap(){map=L.map('map').setView([-33.25,-71.05],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);stations.forEach((s,i)=>{let m=L.marker([s.lat,s.lng],{icon:markerIcon(false)}).addTo(map).bindPopup(`<b>${s.name}</b><br>${s.code}<br>${s.project}`);m.on('click',()=>choose(i));markers.push(m)});let group=L.featureGroup(markers);map.fitBounds(group.getBounds().pad(.2))}
function choose(i){selected=i;$('station-select').value=i;markers.forEach((m,j)=>m.setIcon(markerIcon(i===j)));markers[i].openPopup();renderStation()}
function pathsFor(s,period){let all=Object.entries(s.months||{}).sort();if(period==='all')return all.flatMap(x=>x[1]);let days=period==='24h'?1:period==='7d'?7:30,base=new Date(manifest.updated_at.replace(' ','T')).getTime(),cut=base-days*864e5;return all.filter(([m])=>{let [y,mo]=m.split('-').map(Number);return new Date(y,mo,1).getTime()>=cut}).flatMap(x=>x[1])}
async function rowsFor(s,period){let key=s.code+'|'+period;if(cache[key])return cache[key];let groups=await Promise.all(pathsFor(s,period).map(p=>fetch(p+'?v='+encodeURIComponent(manifest.updated_at)).then(r=>{if(!r.ok)throw Error(r.status);return r.text()}).then(csv)));let rows=groups.flat().sort((a,b)=>new Date(a.fecha)-new Date(b.fecha));if(period!=='all'){let days=period==='24h'?1:period==='7d'?7:30,base=new Date(manifest.updated_at.replace(' ','T')).getTime(),cut=base-days*864e5;rows=rows.filter(r=>new Date(r.fecha)>=cut)}cache[key]=rows;return rows}
function fillVariables(s){let sel=$('variable-select'),current=sel.value;sel.innerHTML='';s.variables.forEach(k=>{if(VARS[k])sel.add(new Option(VARS[k].label,k))});if(s.variables.includes(current))sel.value=current}
async function renderStation(){let s=stations[selected];$('station-title').textContent=s.name;$('station-context').textContent=s.context+' · '+s.project;fillVariables(s);let key=$('variable-select').value,period=$('period-select').value,v=VARS[key];try{let rows=await rowsFor(s,period),points=rows.map(r=>({x:r.fecha,y:num(r[key])})).filter(p=>p.y!==null),live=latest[s.code]?.[key];if(live)points.push({x:live.fecha,y:live.valor});points.sort((a,b)=>new Date(a.x)-new Date(b.x));let last=points.at(-1),n=norm(key,last?.y??null);$('last-value').textContent=last?`${last.y.toLocaleString('es-CL',{maximumFractionDigits:2})} ${v.unit}`:'—';$('last-time').textContent=last?new Date(last.x).toLocaleString('es-CL'):'Sin medición válida';$('norm-state').textContent=n[0];$('norm-detail').textContent=n[1];document.querySelector('.norm').className='metric norm '+n[2];$('availability').textContent=points.length?'Con datos':'Sin datos';$('record-count').textContent=`${points.length.toLocaleString('es-CL')} observaciones válidas`;$('chart-empty').hidden=!!points.length;if(chart)chart.destroy();chart=new Chart($('chart'),{type:'line',data:{datasets:[{label:v.label,data:points,borderColor:v.color,backgroundColor:v.color+'22',fill:true,pointRadius:points.length>150?0:2,tension:.2}]},options:{responsive:true,maintainAspectRatio:false,parsing:false,scales:{x:{type:'category',ticks:{maxTicksLimit:8,callback(i){return new Date(points[i]?.x).toLocaleDateString('es-CL')}},grid:{display:false}},y:{title:{display:true,text:v.unit}}},plugins:{legend:{display:false},tooltip:{callbacks:{title(items){return new Date(items[0].raw.x).toLocaleString('es-CL')}}}}}})}catch(e){console.error(e);$('chart-empty').hidden=false;$('chart-empty').textContent='No fue posible cargar los datos.'}}
function cleanLive(key,value,type){value=num(value);if(value===null)return null;if(key==='ph'&&(value<=0||value>=14))return null;if(key==='conductividad_us_cm'&&value<=0)return null;if(key==='temperatura_agua_c'&&type==='AGUA'&&(value<=0||value>60))return null;return value}
async function liveStation(s){let type=s.code.startsWith('URA')?'URA':'AGUA',url=`${API}?tabla=datos&disp.id_proyecto=${s.project_id}&disp.codigo_interno=${encodeURIComponent(s.code)}&order_by=fecha_insercion&limite=1`;let j=await fetch(url,{cache:'no-store'}).then(r=>r.json()),row=j?.data?.tableData?.[0];if(!row)return;latest[s.code]={};Object.entries(LIVE_FIELDS[type]).forEach(([k,f])=>{let val=cleanLive(k,row[f],type);if(val!==null)latest[s.code][k]={fecha:row.fecha,valor:val}});return row.fecha}
async function refreshLive(){let times=[];for(let s of stations){try{let t=await liveStation(s);if(t)times.push(t)}catch(e){console.warn('En vivo',s.code,e)}}if(times.length){$('live-dot').style.background='#37c694';$('live-label').textContent='Datos en vivo';$('updated').textContent=new Date(times.sort().at(-1)).toLocaleString('es-CL');renderStation()}else{$('live-label').textContent='Histórico horario'}}
function download(name,rows){let keys=Object.keys(rows[0]||{}),text=keys.join(',')+'\n'+rows.map(r=>keys.map(k=>r[k]??'').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function downloadSelection(){if(!confirm('Datos preliminares con incertidumbre y posibles correcciones. El licenciamiento abierto propuesto continúa en revisión. ¿Deseas descargar?'))return;let s=stations[selected],rows=(await rowsFor(s,$('period-select').value)).map(r=>({estacion:s.code,...r}));if(rows.length)download(`${s.code}_${$('period-select').value}.csv`,rows)}
async function downloadAll(){if(!confirm('Descargarás todo el histórico público. Los datos son preliminares y el licenciamiento propuesto continúa en revisión. ¿Deseas continuar?'))return;let button=$('download-all');button.disabled=true;button.textContent='Preparando…';try{let all=[];for(let s of stations)(await rowsFor(s,'all')).forEach(r=>all.push({estacion:s.code,...r}));if(all.length)download('calidad_agua_todos_los_datos.csv',all)}finally{button.disabled=false;button.textContent='Descargar todos los datos'}}
async function init(){let [m,l]=await Promise.all([fetch('data/manifest.json?v='+Date.now()).then(r=>r.json()),fetch('data/latest.csv?v='+Date.now()).then(r=>r.text())]);manifest=m;stations=m.stations;csv(l).forEach(r=>{latest[r.codigo]??={};latest[r.codigo][r.variable]={fecha:r.fecha,valor:num(r.valor)}});$('updated').textContent=m.updated_at?new Date(m.updated_at).toLocaleString('es-CL'):'—';$('station-select').innerHTML=stations.map((s,i)=>`<option value="${i}">${s.name}</option>`).join('');$('station-list').innerHTML=stations.map((s,i)=>`<div class="station-item" data-i="${i}"><span><b>${s.name}</b><br><small>${s.context}</small></span><span class="station-code">${s.code}</span></div>`).join('');document.querySelectorAll('.station-item').forEach(el=>el.onclick=()=>choose(+el.dataset.i));setupMap();choose(0);refreshLive();setInterval(refreshLive,600000)}
$('station-select').onchange=e=>choose(+e.target.value);$('variable-select').onchange=renderStation;$('period-select').onchange=renderStation;$('download-selection').onclick=downloadSelection;$('download-all').onclick=downloadAll;init().catch(e=>{$('live-label').textContent='Datos no disponibles';console.error(e)});
